<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 -T .\turntable_mid.glb
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('model/turntable_mid-transformed.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes.Cube.geometry} material={gltf.materials['Material.002']} />
    <T.Mesh geometry={gltf.nodes.Cube010.geometry} material={gltf.materials['Material.003']} />
    <T.Group scale={[0.4, 0.04, 0.4]}>
      <T.Mesh geometry={gltf.nodes.Cylinder005.geometry} material={gltf.materials['Material.003']} />
      <T.Mesh geometry={gltf.nodes.Cylinder005_1.geometry} material={gltf.materials['Material.001']} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
