<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 -T .\turntable_right.glb
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('model/turntable_right-transformed.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes.Cube007.geometry} material={gltf.materials['Material.003']} />
    <T.Mesh geometry={gltf.nodes.Cube001.geometry} material={gltf.materials['Material.002']} />
    <T.Mesh
      geometry={gltf.nodes.Cube002.geometry}
      material={gltf.materials['Material.002']}
      rotation={[-Math.PI, 0, -Math.PI]}
    />
    <T.Mesh geometry={gltf.nodes.Cube005.geometry} material={gltf.materials['Material.003']} />
    <T.Mesh geometry={gltf.nodes.Cube008.geometry} material={gltf.materials['Material.003']} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
