<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 -T .\turntable_left.glb
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('model/turntable_left-transformed.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Cube011.geometry}
      material={gltf.materials.Material}
      position={[-1.35, 0.03, 0.35]}
      scale={0.05}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube013.geometry}
      material={gltf.materials.Material}
      position={[-1.25, 0.03, 0.35]}
      scale={0.05}
    />
    <T.Mesh
      geometry={gltf.nodes.Cylinder005.geometry}
      material={gltf.materials['Material.001']}
      position={[-1.3, 0, 0.15]}
      scale={0.1}
    />
    <T.Mesh geometry={gltf.nodes.Cube003.geometry} material={gltf.materials['Material.002']} />
    <T.Mesh geometry={gltf.nodes.Cube004.geometry} material={gltf.materials['Material.002']} />
    <T.Mesh geometry={gltf.nodes.Cube006.geometry} material={gltf.materials['Material.005']} position={[-3.05, 0, 0]} />
    <T.Mesh geometry={gltf.nodes.Cube009.geometry} material={gltf.materials['Material.005']} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
