<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 -T .\turntable_arm.glb
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('model/turntable_arm-transformed.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Cylinder002.geometry}
      material={gltf.materials['Material.001']}
      position={[1.3, 0.05, -0.3]}
      scale={0.1}
    />
    <T.Mesh
      geometry={gltf.nodes.Cylinder003.geometry}
      material={gltf.materials['Material.001']}
      position={[1.3, 0.08, -0.3]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={0.03}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
