<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 -T .\vinyl.glb
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('model/vinyl-transformed.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group position={[0, 0.02, 0]} scale={[1, 0.01, 1]}>
      <T.Mesh geometry={gltf.nodes.Cylinder008.geometry} material={gltf.materials['Material.010']} />
      <T.Mesh geometry={gltf.nodes.Cylinder008_1.geometry} material={gltf.materials['Material.010']} />
      <T.Mesh geometry={gltf.nodes.Cylinder008_2.geometry} material={gltf.materials['Material.012']} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
